#!/bin/bash
echo "=== Phoenix Nodes Status ==="
echo ""
echo "Node 1 (port 4000):"
lsof -i :4000 2>/dev/null || echo "  ❌ Not running"
echo ""
echo "Node 2 (port 4001):"
lsof -i :4001 2>/dev/null || echo "  ❌ Not running"
echo ""
echo "Node 3 (port 4002):"
lsof -i :4002 2>/dev/null || echo "  ❌ Not running"
echo ""
echo "Nginx (port 3000):"
lsof -i :3000 2>/dev/null || echo "  ❌ Not running"
echo ""
echo "=== Quick Test ==="
curl -s http://localhost:4000 > /dev/null && echo "✅ Node 1 responding" || echo "❌ Node 1 down"
curl -s http://localhost:4001 > /dev/null && echo "✅ Node 2 responding" || echo "❌ Node 2 down"
curl -s http://localhost:4002 > /dev/null && echo "✅ Node 3 responding" || echo "❌ Node 3 down"
curl -s http://localhost:3000 > /dev/null && echo "✅ Nginx responding" || echo "❌ Nginx down"
